server:
  port: <%= port %>
spring:
  application:
    name: <%= name %>
  data:
    mongodb:
      uri: mongodb://localhost:27017/shop?replicaSet=replicaset
logging:
  level:
    root: info
    org.springframework: info
